export const AUTH = {
  LOGIN: 'LOGIN',
  LOGIN_EXITOSO: 'LOGIN_EXITOSO',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT'
}

export const OPERADOR = {
  GET_OPERADORES: 'GET_OPERADORES',
  GET_OPERADORES_OK: 'GET_OPERADORES_OK',
  GET_OPERADORES_FAIL: 'GET_OPERADORES_FAIL',
  GET_OPERADOR: 'GET_OPERADOR',
  GET_OPERADOR_OK: 'GET_OPERADOR_OK',
  GET_OPERADOR_FAIL: 'GET_OPERADOR_FAIL',
  ADD_OPERADOR: 'ADD_OPERADOR',
  ADD_OPERADOR_OK: 'ADD_OPERADOR_OK',
  ADD_OPERADOR_FAIL: 'ADD_OPERADOR_FAIL',
  UPDATE_OPERADOR_ESTADO: 'UPDATE_OPERADOR_ESTADO',
  UPDATE_OPERADOR_ESTADO_OK: 'UPDATE_OPERADOR_ESTADO_OK',
  UPDATE_OPERADOR_ESTADO_FAIL: 'UPDATE_OPERADOR_ESTADO_FAIL',
  DELETE_OPERADOR: 'DELETE_OPERADOR',
  DELETE_OPERADOR_OK: 'DELETE_OPERADOR_OK',
  DELETE_OPERADOR_ERROR: 'DELETE_OPERADOR_ERROR'
}