export const AUTH = {
  LOGIN: 'LOGIN',
  LOGIN_EXITOSO: 'LOGIN_EXITOSO',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT'
}

export const OPERADOR = {
  GET_OPERADORES: 'GET_OPERADORES',
  GET_OPERADORES_OK: 'GET_OPERADORES_OK',
  GET_OPERADORES_FAIL: 'GET_OPERADORES_FAIL',
  GET_OPERADOR: 'GET_OPERADOR',
  GET_OPERADOR_OK: 'GET_OPERADOR_OK',
  GET_OPERADOR_FAIL: 'GET_OPERADOR_FAIL',
  ADD_OPERADOR: 'ADD_OPERADOR',
  ADD_OPERADOR_OK: 'ADD_OPERADOR_OK',
  ADD_OPERADOR_FAIL: 'ADD_OPERADOR_FAIL',
  UPDATE_OPERADOR_ESTADO: 'UPDATE_OPERADOR_ESTADO',
  UPDATE_OPERADOR_ESTADO_OK: 'UPDATE_OPERADOR_ESTADO_OK',
  UPDATE_OPERADOR_ESTADO_FAIL: 'UPDATE_OPERADOR_ESTADO_FAIL',
  UPDATE_OPERADOR: 'UPDATE_OPERADOR',
  UPDATE_OPERADOR_OK: 'UPDATE_OPERADOR_OK',
  UPDATE_OPERADOR_FAIL: 'UPDATE_OPERADOR_FAIL',
  DELETE_OPERADOR: 'DELETE_OPERADOR',
  DELETE_OPERADOR_OK: 'DELETE_OPERADOR_OK',
  DELETE_OPERADOR_ERROR: 'DELETE_OPERADOR_ERROR',
  GET_PERFILES: 'GET_PERFILES',
  GET_PERFILES_OK: 'GET_PERFILES_OK',
  GET_PERFILES_FAIL: 'GET_PERFILES_FAIL'
}

export const CLIENTES = {
  ADD_CLIENTE: 'ADD_CLIENTE',
  ADD_CLIENTE_OK: 'ADD_CLIENTE_OK',
  ADD_CLIENTE_ERROR: 'ADD_CLIENTE_ERROR',
  GET_CLIENTE: 'GET_CLIENTE',
  GET_CLIENTE_OK: 'GET_CLIENTE_OK',
  GET_CLIENTE_FAIL: 'GET_CLIENTE_FAIL',
  UPDATE_CLIENTE: 'UPDATE_CLIENTE',
  UPDATE_CLIENTE_OK: 'UPDATE_CLIENTE_OK',
  UPDATE_CLIENTE_FAIL: 'UPDATE_CLIENTE_FAIL',
  DELETE_CLIETE: 'DELETE_CLIENTE',
  DELETE_CLIENTE_OK: 'DELETE_CLIENTE_OK',
  DELETE_CLIENTE_FAIL: 'DELETE_CLIENTE_FAIL'
}